### ISSUE TITLE
 "use_netpoll_mode": true, 服务不可用

### ISSUE THREAD

**Issue by bamboox** [sofastack/sofa-mosn#729]
### Describe the bug
开启use_netpoll_mode服务报错

### Actual behavior
goroutine panic: runtime error: invalid memory address or nil pointer dereference
goroutine 27 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/home/bamboo/tool/go/src/runtime/debug/stack.go:24 +0xa1
sofastack.io/sofa-mosn/pkg/utils.GoWithRecover.func1.1(0x0)
	/home/bamboo/xxx/go/src/sofastack.io/sofa-mosn/pkg/utils/goroutine.go:35 +0xcc
panic(0x1485160, 0x21b5a30)
	/home/bamboo/tool/go/src/runtime/panic.go:522 +0x1e0
sofastack.io/sofa-mosn/pkg/network.(*eventLoop).registerRead(0x0, 0xc00040c000, 0xc00026df80, 0x0, 0x0)
	/home/bamboo/xxx/go/src/sofastack.io/sofa-mosn/pkg/network/eventloop.go:116 +0x136
sofastack.io/sofa-mosn/pkg/network.(*connection).attachEventLoop(0xc00040c000, 0x17a4c20, 0xc0003a0140)
	/home/bamboo/xxx/go/src/sofastack.io/sofa-mosn/pkg/network/connection.go:168 +0x235
sofastack.io/sofa-mosn/pkg/network.(*connection).Start.func1()
	/home/bamboo/xxx/go/src/sofastack.io/sofa-mosn/pkg/network/connection.go:155 +0x5b
sync.(*Once).Do(0xc00040c190, 0xc000149a00)
	/home/bamboo/tool/go/src/sync/once.go:44 +0xe0
sofastack.io/sofa-mosn/pkg/network.(*connection).Start(0xc00040c000, 0x17a4c20, 0xc0003a0140)
	/home/bamboo/xxx/go/src/sofastack.io/sofa-mosn/pkg/network/connection.go:153 +0x9a
sofastack.io/sofa-mosn/pkg/server.(*activeListener).OnNewConnection(0xc00037c540, 0x17a4c20, 0xc0003a0140, 0x17b78e0, 0xc00040c000)
	/home/bamboo/xxx/go/src/sofastack.io/sofa-mosn/pkg/server/handler.go:468 +0x733
sofastack.io/sofa-mosn/pkg/server.(*activeListener).newConnection(0xc00037c540, 0x17a4c20, 0xc0003a0140, 0x17afa60, 0xc0000c6018)
	/home/bamboo/xxx/go/src/sofastack.io/sofa-mosn/pkg/server/handler.go:493 +0x25c
sofastack.io/sofa-mosn/pkg/server.(*activeRawConn).ContinueFilterChain(0xc0003f4180, 0x17a4c20, 0xc0003a0140, 0x15d7401)
	/home/bamboo/xxx/go/src/sofastack.io/sofa-mosn/pkg/server/handler.go:579 +0x211
sofastack.io/sofa-mosn/pkg/server.(*activeListener).OnAccept(0xc00037c540, 0x17afa60, 0xc0000c6018, 0x432f00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/bamboo/xxx/go/src/sofastack.io/sofa-mosn/pkg/server/handler.go:435 +0x9c6
sofastack.io/sofa-mosn/pkg/network.(*listener).accept.func1()
	/home/bamboo/xxx/go/src/sofastack.io/sofa-mosn/pkg/network/listener.go:190 +0x9b
sofastack.io/sofa-mosn/pkg/utils.GoWithRecover.func1(0x0, 0xc00026cc60)
	/home/bamboo/xxx/go/src/sofastack.io/sofa-mosn/pkg/utils/goroutine.go:51 +0x4f
created by sofastack.io/sofa-mosn/pkg/utils.GoWithRecover
	/home/bamboo/xxx/go/src/sofastack.io/sofa-mosn/pkg/utils/goroutine.go:30 +0x49
### Environment
+ SOFAMosn Version 最新版本

**Comment by neverhook** [comment]
pkg/network/eventloop.go 中的 init 方法默认处于注释状态，使用 netpoll 模式前需要先恢复该段初始化逻辑。

注释的原因比较复杂，我们发现在研发过程中使用 goland 的 debug 模式时，mac 环境下开启 netpoll 有概率会触发 kqueue 返回超大异常值，从而导致 panic，目前根因暂不明确
