### ISSUE TITLE
about ```make image``` occurs exception,thanks

### ISSUE THREAD

**Issue by liyork** [sofastack/sofa-mosn#827]
### Your question

when i exe command flowing the quick start ,but meets the problem when  
```make image```, the exception under:

```
Step 12/27 : RUN easy_install supervisor==3.4.0
 ---> Running in 6b8a9c7cedb5
Searching for supervisor==3.4.0
Reading https://pypi.python.org/simple/supervisor/
Best match: supervisor 3.4.0
Downloading https://files.pythonhosted.org/packages/19/0a/7eef85a26f8dfb585f312e4c6b76b0b16fe800ffce8a4724a7bda6ef440d/supervisor-3.4.0.tar.gz#sha256=31102eeb323fbe57384d6a3746beab8f9ae9db705cdbd04a0861d21e38907a45
Processing supervisor-3.4.0.tar.gz
Running supervisor-3.4.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-V_xQZJ/supervisor-3.4.0/egg-dist-tmp-kWMnSE
warning: no previously-included files matching '*' found under directory 'docs/.build'
Adding supervisor 3.4.0 to easy-install.pth file
Installing echo_supervisord_conf script to /usr/bin
Installing pidproxy script to /usr/bin
Installing supervisorctl script to /usr/bin
Installing supervisord script to /usr/bin

Installed /usr/lib/python2.6/site-packages/supervisor-3.4.0-py2.6.egg
Processing dependencies for supervisor==3.4.0
Searching for meld3>=0.6.5
Reading https://pypi.python.org/simple/meld3/
Best match: meld3 2.0.0
Downloading https://files.pythonhosted.org/packages/00/3b/023446ddc1bf0b519c369cbe88269c30c6a64bd10af4817c73f560c302f7/meld3-2.0.0.tar.gz#sha256=1efda676264490db2e30bfb81b27a918cc6d9c2de6d609491aa43410b9537eb9
Processing meld3-2.0.0.tar.gz
Running meld3-2.0.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-DfGTlW/meld3-2.0.0/egg-dist-tmp-wFiOz6
Traceback (most recent call last):
  File "/usr/bin/easy_install", line 9, in <module>
    load_entry_point('distribute==0.6.10', 'console_scripts', 'easy_install')()
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 1715, in main
    with_ei_usage(lambda:
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 1696, in with_ei_usage
    return f()
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 1719, in <lambda>
    distclass=DistributionWithoutHelpCommands, **kw
  File "/usr/lib64/python2.6/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.6/distutils/dist.py", line 975, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 236, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 472, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 504, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 545, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 538, in resolve
    dist = best[req.key] = env.best_match(req, self, installer)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 780, in best_match
    return self.obtain(req, installer) # try and download/install
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 792, in obtain
    return installer(requirement)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 472, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 502, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 681, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 958, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 947, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.6/site-packages/setuptools/sandbox.py", line 29, in run_setup
    lambda: execfile(
  File "/usr/lib/python2.6/site-packages/setuptools/sandbox.py", line 70, in run
    return func()
  File "/usr/lib/python2.6/site-packages/setuptools/sandbox.py", line 31, in <lambda>
    {'__file__':setup_script, '__name__':'__main__'}
  File "setup.py", line 7, in <module>
RuntimeError: On Python 2, meld3 requires Python 2.7 or later
The command '/bin/sh -c easy_install supervisor==3.4.0' returned a non-zero code: 1
make: *** [image] Error 1
```

so i try to solve it by below method:
a. let the docker image of python 3.5
b. see the Downloading https://xxx  file and see
c. run /bin/sh -c easy_install supervisor==3.4.0 in local mac os
d. and soso .
but not solve it ,final. 
i am a newer in go and mosn,thanks for take care of the issue.thans.

### Environment
+ SOFAMosn Version master
mac os 
docker for mac ,Engine: 19.03.2  ,Kubernetes: v1.14.6 ,Machine: 0.16.2

**Comment by nejisama** [comment]
maybe it is the network question.  please use the dockerfile below to replace dockerfile "build/contrib/builder/image/Dockerfile"
```
FROM centos:centos7
MAINTAINER  xiaodong.dxd@alibaba-inc.com

ENV TMP_FOLDER      /tmp
ENV GIT_USER        alipay
ENV MOSN_PREFIX     /home/admin/mosn
ENV PATH            $MOSN_PREFIX/sbin:$PATH

RUN mkdir -p $MOSN_PREFIX/conf
RUN mkdir -p $MOSN_PREFIX/logs

RUN yum install -y \
       ssh wget curl perl logrotate make build-essential procps \
       tsar tcpdump mpstat iostat vmstat sysstat \
       python-setuptools; yum clean all 

# 规避crond在docker环境下运行的问题
RUN echo -e "sleep 10;/bin/touch /var/spool/cron/a;/bin/rm -f /var/spool/cron/a;service crond restart" > /opt/fix-cron.sh

COPY ./etc/script/entrypoint.sh     /usr/local/bin/entrypoint.sh

# pip
WORKDIR $TMP_FOLDER
RUN wget https://mirrors.aliyun.com/pypi/packages/69/81/52b68d0a4de760a2f1979b0931ba7889202f302072cc7a0d614211bc7579/pip-18.0.tar.gz#sha256=a0e11645ee37c90b40c46d607070c4fd583e2cd46231b1c06e389c5e814eed76RUN tar zvxf pip-18.0.tar.gz
WORKDIR $TMP_FOLDER/pip-18.0
RUN python setup.py install

# supervisor
RUN pip install supervisor -i https://mirrors.aliyun.com/pypi/simple
RUN pip install supervisor-stdout -i https://mirrors.aliyun.com/pypi/simple

RUN echo "export MOSN_PREFIX=/home/admin/mosn" >> /etc/bashrc;
RUN echo "export PATH=$PATH" >> /etc/bashrc

COPY ./etc/supervisor/supervisord.conf            /etc/supervisord.conf
COPY ./etc/supervisor/mosn.conf                   /etc/supervisord/conf.d/mosn.conf
COPY ./etc/mosn/mosn.logrotate                    /etc/logrotate.d/mosn
RUN mv /etc/cron.daily/logrotate                  /etc/cron.hourly/logrotate

EXPOSE 22 80

ADD ./mosnd $MOSN_PREFIX/sbin

ENTRYPOINT ["/usr/bin/supervisord" , "-c" , "/etc/supervisord.conf"]

```

**Comment by nejisama** [comment]
1. change base image to centos7 instead of centos6, use python 2.7+
2. use aliyun to install supervisor,  instead of official

**Comment by nejisama** [comment]
#828

**Comment by liyork** [comment]
hi  nejisama ,
thanks your help.

i try replace the dockerfile and then ```make image```
but got this new error:

```
Step 12/26 : WORKDIR $TMP_FOLDER
 ---> Running in 8f0b6b15b78f
Removing intermediate container 8f0b6b15b78f
 ---> c4275c6901b4
Step 13/26 : RUN wget https://mirrors.aliyun.com/pypi/packages/69/81/52b68d0a4de760a2f1979b0931ba7889202f302072cc7a0d614211bc7579/pip-18.0.tar.gz#sha256=a0e11645ee37c90b40c46d607070c4fd583e2cd46231b1c06e389c5e814eed76RUN tar zvxf pip-18.0.tar.gz
 ---> Running in 322318a0ff59
--2019-09-25 09:26:30--  https://mirrors.aliyun.com/pypi/packages/69/81/52b68d0a4de760a2f1979b0931ba7889202f302072cc7a0d614211bc7579/pip-18.0.tar.gz
Resolving mirrors.aliyun.com (mirrors.aliyun.com)... 47.246.16.229, 47.91.195.229, 47.246.16.230, ...
Connecting to mirrors.aliyun.com (mirrors.aliyun.com)|47.246.16.229|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1249656 (1.2M) [application/gzip]
Saving to: 'pip-18.0.tar.gz'

     0K .......... .......... .......... .......... ..........  4% 42.3K 28s
    50K .......... .......... .......... .......... ..........  8% 28.4K 33s
   100K .......... .......... .......... .......... .......... 12% 37.7K 30s
   150K .......... .......... .......... .......... .......... 16% 21.9K 33s
   200K .......... .......... .......... .......... .......... 20% 14.8K 39s
   250K .......... .......... .......... .......... .......... 24% 26.8M 30s
   300K .......... .......... .......... .......... .......... 28% 24.0K 30s
   350K .......... .......... .......... .......... .......... 32% 29.5K 28s
   400K .......... .......... .......... .......... .......... 36% 15.7K 29s
   450K .......... .......... .......... .......... .......... 40%  348K 25s
   500K .......... .......... .......... .......... .......... 45% 30.9K 23s
   550K .......... .......... .......... .......... .......... 49% 18.0K 22s
   600K .......... .......... .......... .......... .......... 53% 53.3K 20s
   650K .......... .......... .......... .......... .......... 57% 21.7K 18s
   700K .......... .......... .......... .......... .......... 61% 21.6K 17s
   750K .......... .......... .......... .......... .......... 65% 35.5K 15s
   800K .......... .......... .......... .......... .......... 69% 21.0K 13s
   850K .......... .......... .......... .......... .......... 73% 25.3K 12s
   900K .......... .......... .......... .......... .......... 77% 16.6K 10s
   950K .......... .......... .......... .......... .......... 81% 22.3K 8s
  1000K .......... .......... .......... .......... .......... 86% 17.4K 7s
  1050K .......... .......... .......... .......... .......... 90% 49.3K 5s
  1100K .......... .......... .......... .......... .......... 94% 25.5K 3s
  1150K .......... .......... .......... .......... .......... 98% 20.2K 1s
  1200K .......... ..........                                 100% 17.5K=47s

2019-09-25 09:27:19 (25.7 KB/s) - 'pip-18.0.tar.gz' saved [1249656/1249656]

--2019-09-25 09:27:19--  http://tar/
Resolving tar (tar)... failed: Name or service not known.
wget: unable to resolve host address 'tar'
--2019-09-25 09:27:20--  http://zvxf/
Resolving zvxf (zvxf)... failed: Name or service not known.
wget: unable to resolve host address 'zvxf'
--2019-09-25 09:27:21--  http://pip-18.0.tar.gz/
Resolving pip-18.0.tar.gz (pip-18.0.tar.gz)... failed: Name or service not known.
wget: unable to resolve host address 'pip-18.0.tar.gz'
FINISHED --2019-09-25 09:27:21--
Total wall clock time: 51s
Downloaded: 1 files, 1.2M in 47s (25.7 KB/s)
The command '/bin/sh -c wget https://mirrors.aliyun.com/pypi/packages/69/81/52b68d0a4de760a2f1979b0931ba7889202f302072cc7a0d614211bc7579/pip-18.0.tar.gz#sha256=a0e11645ee37c90b40c46d607070c4fd583e2cd46231b1c06e389c5e814eed76RUN tar zvxf pip-18.0.tar.gz' returned a non-zero code: 4
make: *** [image] Error 4
```

i try config the docker Registry mirrors adding into the https://mirrors.aliyun.com
and i can get the file from http in my mac,
so if the docker need config or else?

thanks.

**Comment by liyork** [comment]
i try it again ,but get the error:

```
Step 12/26 : WORKDIR $TMP_FOLDER
 ---> Running in 616bb0f47855
Removing intermediate container 616bb0f47855
 ---> 126e476a57b4
Step 13/26 : RUN wget https://mirrors.aliyun.com/pypi/packages/69/81/52b68d0a4de760a2f1979b0931ba7889202f302072cc7a0d614211bc7579/pip-18.0.tar.gz#sha256=a0e11645ee37c90b40c46d607070c4fd583e2cd46231b1c06e389c5e814eed76RUN tar zvxf pip-18.0.tar.gz
 ---> Running in dfc3b284505c
--2019-09-25 12:45:51--  https://mirrors.aliyun.com/pypi/packages/69/81/52b68d0a4de760a2f1979b0931ba7889202f302072cc7a0d614211bc7579/pip-18.0.tar.gz
Resolving mirrors.aliyun.com (mirrors.aliyun.com)... 124.239.227.223, 219.147.83.249, 219.147.83.245, ...
Connecting to mirrors.aliyun.com (mirrors.aliyun.com)|124.239.227.223|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1249656 (1.2M) [application/gzip]
Saving to: 'pip-18.0.tar.gz'

     0K .......... .......... .......... .......... ..........  4%  740K 2s
    50K .......... .......... .......... .......... ..........  8% 2.39M 1s
   100K .......... .......... .......... .......... .......... 12% 4.80M 1s
   150K .......... .......... .......... .......... .......... 16% 19.5M 1s
   200K .......... .......... .......... .......... .......... 20% 2.62M 0s
   250K .......... .......... .......... .......... .......... 24% 14.9M 0s
   300K .......... .......... .......... .......... .......... 28% 17.6M 0s
   350K .......... .......... .......... .......... .......... 32% 3.07M 0s
   400K .......... .......... .......... .......... .......... 36% 1.60M 0s
   450K .......... .......... .......... .......... .......... 40% 2.00M 0s
   500K .......... .......... .......... .......... .......... 45% 2.08M 0s
   550K .......... .......... .......... .......... .......... 49% 2.03M 0s
   600K .......... .......... .......... .......... .......... 53%  134K 1s
   650K .......... .......... .......... .......... .......... 57% 3.09M 0s
   700K .......... .......... .......... .......... .......... 61% 2.74M 0s
   750K .......... .......... .......... .......... .......... 65% 12.1M 0s
   800K .......... .......... .......... .......... .......... 69% 15.5M 0s
   850K .......... .......... .......... .......... .......... 73% 6.75M 0s
   900K .......... .......... .......... .......... .......... 77% 7.80M 0s
   950K .......... .......... .......... .......... .......... 81% 8.62M 0s
  1000K .......... .......... .......... .......... .......... 86% 21.3M 0s
  1050K .......... .......... .......... .......... .......... 90% 86.4K 0s
  1100K .......... .......... .......... .......... .......... 94% 2.24M 0s
  1150K .......... .......... .......... .......... .......... 98% 37.1M 0s
  1200K .......... ..........                                 100% 1.68M=1.3s

2019-09-25 12:45:53 (945 KB/s) - 'pip-18.0.tar.gz' saved [1249656/1249656]

--2019-09-25 12:45:53--  http://tar/
Resolving tar (tar)... failed: Name or service not known.
wget: unable to resolve host address 'tar'
--2019-09-25 12:45:54--  http://zvxf/
Resolving zvxf (zvxf)... failed: Name or service not known.
wget: unable to resolve host address 'zvxf'
--2019-09-25 12:45:55--  http://pip-18.0.tar.gz/
Resolving pip-18.0.tar.gz (pip-18.0.tar.gz)... failed: Name or service not known.
wget: unable to resolve host address 'pip-18.0.tar.gz'
FINISHED --2019-09-25 12:45:55--
Total wall clock time: 3.6s
Downloaded: 1 files, 1.2M in 1.3s (945 KB/s)
The command '/bin/sh -c wget https://mirrors.aliyun.com/pypi/packages/69/81/52b68d0a4de760a2f1979b0931ba7889202f302072cc7a0d614211bc7579/pip-18.0.tar.gz#sha256=a0e11645ee37c90b40c46d607070c4fd583e2cd46231b1c06e389c5e814eed76RUN tar zvxf pip-18.0.tar.gz' returned a non-zero code: 4
make: *** [image] Error 4
```

i guess this may be not the network,
i see this :
```
--2019-09-25 12:45:53--  http://tar/
Resolving tar (tar)... failed: Name or service not known.
wget: unable to resolve host address 'tar'
```
and then in dockerfile has this line:

```
RUN wget https://mirrors.aliyun.com/pypi/packages/69/81/52b68d0a4de760a2f1979b0931ba7889202f302072cc7a0d614211bc7579/pip-18.0.tar.gz#sha256=a0e11645ee37c90b40c46d607070c4fd583e2cd46231b1c06e389c5e814eed76RUN tar zvxf pip-18.0.tar.gz
```

it may using two ```RUN``  command ?

thanks.

**Comment by nejisama** [comment]
@liyork  sorry, copy lose a enter('\n')
you can see the pull request #828

**Comment by nejisama** [comment]
the dockerfile in the comment is updated.

**Comment by liyork** [comment]
hi,i may try the resolve,
update this below:

```
RUN wget https://mirrors.aliyun.com/pypi/packages/69/81/52b68d0a4de760a2f1979b0931ba7889202f302072cc7a0d614211bc7579/pip-18.0.tar.gz#sha256=a0e11645ee37c90b40c46d607070c4fd583e2cd46231b1c06e389c5e814eed76RUN
RUN tar zvxf pip-18.0.tar.gz
```

**Comment by liyork** [comment]
o,i see this change history.
thank you.
helping me a lot.

**Comment by liyork** [comment]
thanks.i see the changelog
